"""Öffentliche API für Gamma- und WebSocket-Schnittstellen."""

# ============================================================================
# Stabile öffentliche Schnittstelle
# ============================================================================
# Bot-Komponenten importieren Gamma- und WebSocket-Typen über dieses Paket.

from .gamma_api import (
    GAMMA_API_BASE,
    ApiType,
    ErrorCode,
    EventSearchParams,
    GammaAPI,
    GammaEvent,
    GammaMarket,
    MarketSearchParams,
    PolymarketError,
    RateLimiter,
    UnifiedCache,
)
from .polymarket_websocket import (
    MARKET_WEBSOCKET_URL,
    BestBidAskEvent,
    BookEvent,
    ConnectionState,
    LastTradePriceEvent,
    MarketEvent,
    MarketEventMessage,
    MarketEventParser,
    MarketEventType,
    MarketResolvedEvent,
    MarketWebSocketClient,
    MarketWebSocketConfig,
    NewMarketEvent,
    OrderBookLevel,
    OrderBookStore,
    OrderBookView,
    PolymarketWebSocketError,
    PriceChangeEvent,
    PriceLevelChange,
    ReconnectPolicy,
    Side,
    TickSizeChangeEvent,
    UnknownMarketEvent,
    WebSocketErrorCode,
)

__all__ = [
    "GAMMA_API_BASE",
    "MARKET_WEBSOCKET_URL",
    "ApiType",
    "BestBidAskEvent",
    "BookEvent",
    "ConnectionState",
    "ErrorCode",
    "EventSearchParams",
    "GammaAPI",
    "GammaEvent",
    "GammaMarket",
    "LastTradePriceEvent",
    "MarketEvent",
    "MarketEventMessage",
    "MarketEventParser",
    "MarketEventType",
    "MarketResolvedEvent",
    "MarketSearchParams",
    "MarketWebSocketClient",
    "MarketWebSocketConfig",
    "NewMarketEvent",
    "OrderBookLevel",
    "OrderBookStore",
    "OrderBookView",
    "PolymarketError",
    "PolymarketWebSocketError",
    "PriceChangeEvent",
    "PriceLevelChange",
    "RateLimiter",
    "ReconnectPolicy",
    "Side",
    "TickSizeChangeEvent",
    "UnifiedCache",
    "UnknownMarketEvent",
    "WebSocketErrorCode",
]
